# Generated by Django 4.1.5 on 2023-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('MINUTE', 'Minute/s'), ('HOUR', 'Hour/s')], default='MINUTE', max_length=10),
        ),
    ]
