# Generated by Django 4.1.5 on 2023-01-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_preparation_time_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(choices=[('PLATES', 'Plate/s'), ('PEOPLE', 'People/s')], default='PLATES', max_length=10),
        ),
    ]
