# Generated by Django 4.1.5 on 2023-01-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_serving_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='san-wi-ch'),
            preserve_default=False,
        ),
    ]
