# Generated by Django 4.1.5 on 2023-01-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
