# Generated by Django 4.1.5 on 2023-01-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_serving_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('MINUTO/S', 'Minuto/s'), ('HORA/S', 'Hora/s')], default='MINUTO/S', max_length=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(choices=[('PRATO/S', 'Pratos/s'), ('PESSOA/S', 'Pratos/s')], default='PESSOA/S', max_length=15),
        ),
    ]
