# Generated by Django 4.1.5 on 2023-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_preparation_time_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(choices=[('PRATO/S', 'Pratos/s'), ('PESSOA/S', 'Pessoas/s')], default='PESSOA/S', max_length=15),
        ),
    ]
