# Generated by Django 4.1.5 on 2023-01-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_serving_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='serving_unit',
            new_name='servings_unit',
        ),
    ]
