# Generated by Django 4.1.5 on 2023-01-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_serving_unit_recipe_servings_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('Minuto/s', 'Minuto/s'), ('Hora/s', 'Hora/s')], default='MINUTO/S', max_length=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(choices=[('Pessoas/s', 'Pessoas/s')], default='PESSOA/S', max_length=15),
        ),
    ]
