# Generated by Django 4.1.5 on 2023-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_preparation_time_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('Minuto/s', 'Minuto/s'), ('Hora/s', 'Hora/s')], default='Minuto/s', max_length=65),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(choices=[('Pessoas/s', 'Pessoas/s')], default='Pessoas/s', max_length=65),
        ),
    ]
