# Generated by Django 4.1.5 on 2023-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_preparation_time_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(choices=[('Pessoa/s', 'Pessoa/s'), ('Prato/s', 'Prato/s')], default='Prato/s', max_length=65),
        ),
    ]
